dist: trusty
sudo: false
language: rust

# Based on https://levans.fr/rust_travis_cache.html
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

stages:
- test
- name: deploy
  if: branch = master
jobs:
  allow_failures:
    - rust: nightly
  include:
  - stage: test
    rust: stable
    before_script:
      - rustup component add rustfmt-preview
      - rustup component add clippy-preview
    script:
      - cargo fmt -- --check
      - cargo build --all
      - cargo clippy
      - cargo test --all
  - stage: test
    rust: beta
    script: cargo build --all && cargo test --all
  - stage: test
    name: web
    rust: stable
    before_script: which cargo-web || cargo install cargo-web
    script: cargo web build
  - stage: test
    rust: nightly
    script: cargo build --all && cargo test --all
  - name: minimal versions check
    stage: test
    rust: nightly
    script: rm Cargo.lock && cargo build -Z minimal-versions --tests
  - stage: deploy
    if: branch = master AND type != pull_request
    rust: stable
    before_script: which cargo-web || cargo install cargo-web
    script: cargo web deploy && GIT_DEPLOY_DIR=./target/deploy ./deploy.sh
    env:
      - secure: SaFndhRf92KNdqIQo0XOYzXVdMiMZz03lmghoG0w5sE46wOK7RUsP50ujFVKVHHohV6GhFX4+FYbQXoJzI4SdwFBQP/q+82qdM69wHVikXsi4eilS7zZ3SduuzWxL0+g279k551Jt+ZoiY6QT0hVljCYcHxj43hwMglkqGNEFfrXTsRq7AogC3Dm5aJud8pUMrmfePyQnVWfVUZDuv5y+MmgunC6zpiT9Onezbaq+rHDvFboVQe5shm4/+QWdERQ0i6oyfqKCcTFaZx9YznCuiuT0HqqKZcPSUZMaBJj7gZMeJuO9Bf3EDvuvfWtoW8YUVpyNkvTcz1WAjlhzcAGvOCAUWGXawy7b7lZGZOiiz0XLejbuPgjPZhkephBe44fUzyQfT2PYGSBVMIICPx8mTzGh4HmRFw5JEg4YLI9LXFbLHNZDcOg8sxnP6cmggVWiUt+TQwcyC9dlLBbBgf2WpT6uTD2yP4gKBN+DR9BBl+3Rwl7NHxcSiELAdBlVJBqt+a0eFxHU6pX9MdSjTqyM8Xh5vlb7Bsx3A5VQkHl4/CdeuwG4kIGdFJ/Z6Ftfi3mImtljRZXBEylSa3w55BnSdvoZVZiZm+4dar7LxtlmOGy1LL7fDFqI0QV1dyu+bMLu9B8qwo47N7H4WPMSkOI/OO4Wtz2mWuchqNF5XQJNzw=
  fast_finish: true