dist: trusty
sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --all
  - cargo test --all