[package]
name = "maiden"
version = "0.1.0"
authors = ["Tom Parker <palfrey@tevp.net>"]

[dependencies]
nom = "4"
log = "0.4"
pretty_env_logger = "0.2"
error-chain = "0.12"
clap = "2"
assert_cmd = "0.6"
regex = "1"
num-bigint = "0.2"
num-traits = "0.2"