[package]
name = "maiden"
version = "0.1.0"
authors = ["Tom Parker <palfrey@tevp.net>"]

[dependencies]
nom = "4"
nom_locate = "0.3"
log = "0.4"
pretty_env_logger = "0.2"
error-chain = "0.12"
clap = "2"
assert_cmd = "0.6"
regex = "1"

[target.wasm32-unknown-unknown.dependencies]
yew = { git = "https://github.com/DenisKolodin/yew", rev="7e921ffae" } # For ComponentLink. Replace with 0.5
stdweb = "0.4.5"

[profile.release]
lto = true
opt-level = 's'